<script lang="ts">
	// B102-R4/R5 — structured /docs/api view driven by the generated manifest.
	//
	// Renders one <SignatureBlock> per public export (extracted signature +
	// TSDoc description) inside a <DocPage>, whose right-rail "On this page" TOC
	// is derived from the per-symbol <h2> headings. Parameterised symbols also
	// render a <ParameterTable>. The manifest is generated by `pnpm docs:generate`
	// from the `src/` TSDoc + types — never hand-authored (see scripts/docs/).

	import DocPage from '$lib/docs/widgets/DocPage.svelte';
	import SignatureBlock from '$lib/docs/widgets/SignatureBlock.svelte';
	import ParameterTable from '$lib/docs/widgets/ParameterTable.svelte';
	import { API_MANIFEST } from '$lib/docs/api/manifest.generated.js';

	// Manifest examples are stored as fenced TSDoc blocks (```ts … ```); strip
	// the fence so the body renders cleanly inside a <pre><code>.
	function exampleCode(example: string): string {
		return example
			.replace(/^```[a-zA-Z]*\n?/, '')
			.replace(/\n?```$/, '')
			.trim();
	}
</script>

<DocPage title="API Reference" sidebarGroup="reference" order={1}>
	{#each API_MANIFEST as sym (sym.name)}
		<section aria-label={sym.name} class="api-symbol">
			<h2 id={sym.name}>{sym.name}</h2>
			<SignatureBlock signature={sym.signature} description={sym.description} />
			{#if sym.parameters && sym.parameters.length > 0}
				<ParameterTable rows={sym.parameters} />
			{/if}
			{#if sym.examples.length > 0}
				<div class="examples">
					<p class="examples-label">Example</p>
					{#each sym.examples as example}
						<pre class="example"><code>{exampleCode(example)}</code></pre>
					{/each}
				</div>
			{/if}
		</section>
	{/each}
</DocPage>

<style>
	.api-symbol {
		margin-bottom: var(--u3);
		/* Don't let a wide signature/table establish an intrinsic min-width
		   that stretches the prose column and pushes the TOC off-screen. */
		min-width: 0;
	}
	.api-symbol h2 {
		font-family: var(--mono);
		scroll-margin-top: var(--u3);
	}
	.examples {
		margin-top: var(--u2);
		min-width: 0;
	}
	.examples-label {
		font-size: 11px;
		color: var(--ink-dim);
		text-transform: uppercase;
		letter-spacing: 0.05em;
		margin-bottom: var(--u);
	}
	.example {
		margin: 0 0 12px;
		font-family: var(--mono);
		font-size: 13px;
		color: var(--ink);
		background: var(--bg-rail);
		padding: 12px;
		border-radius: 6px;
		border: 1px solid var(--rule);
		overflow-x: auto;
		min-width: 0;
	}
	.example code {
		background: none;
		color: inherit;
		font-family: inherit;
		padding: 0;
	}
</style>
