/**
 * B126 — build-time highlight of every docs code sample.
 *
 * Build-time only (D13-exempt). Runs each sample in `src/lib/docs/samples.ts` through the
 * warm Shiki + Twoslash highlighter (`twoslash-highlight.ts`): type-checks it (a broken
 * sample REJECTS → the build fails, B126-R2), highlights it with the site dual themes, and
 * injects the clickable type-links (B126-R3). Emits two GENERATED, plain runtime-agnostic
 * modules the client imports:
 *
 *  - `src/lib/docs/api/samples.generated.ts` — `SAMPLES: Record<id, html>` (the
 *    pre-highlighted, twoslash-linked HTML `<CodeSample>` renders).
 *  - `src/lib/docs/api/sample-links.generated.ts` — `SAMPLE_LINKS` (every emitted type-link),
 *    which the dangling-link guard validates against the /docs/api anchor set (B126-R6).
 *
 * Nothing from twoslash enters the emitted modules — they are plain serializable data.
 */

import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync } from "node:fs";
import { createSampleHighlighter, type EmittedLink } from "./twoslash-highlight.js";
import { DOC_SAMPLES } from "../src/lib/docs/samples.js";

const here = dirname(fileURLToPath(import.meta.url));
const siteRoot = resolve(here, "..");
const SAMPLES_OUT = join(siteRoot, "src", "lib", "docs", "api", "samples.generated.ts");
const LINKS_OUT = join(siteRoot, "src", "lib", "docs", "api", "sample-links.generated.ts");

interface SampleLinkRow {
  text: string;
  anchor: string;
  sample: string;
}

async function main(): Promise<void> {
  const highlighter = createSampleHighlighter();
  const htmlById: Record<string, string> = {};
  const links: SampleLinkRow[] = [];

  for (const sample of DOC_SAMPLES) {
    let result: { html: string; links: EmittedLink[] };
    try {
      result = await highlighter.highlightSampleWithLinks(sample.source);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      // eslint-disable-next-line no-console -- build-time fatal
      console.error(`build-samples: sample '${sample.id}' failed:\n  ${message}`);
      process.exit(1);
    }
    htmlById[sample.id] = result.html;
    for (const link of result.links) {
      links.push({ text: link.text, anchor: link.anchor, sample: sample.id });
    }
  }

  const samplesHeader = `/**
 * GENERATED by \`pnpm build-samples\` (site/scripts/build-samples.ts) — DO NOT EDIT.
 * Each value is the build-time Shiki + Twoslash highlighted, type-link-injected HTML of a
 * docs sample (source of truth: src/lib/docs/samples.ts). Plain runtime-agnostic data (D13).
 */

export const SAMPLES: Record<string, string> = `;
  writeFileSync(SAMPLES_OUT, samplesHeader + JSON.stringify(htmlById, null, 2) + ";\n", "utf8");

  const linksHeader = `/**
 * GENERATED by \`pnpm build-samples\` (site/scripts/build-samples.ts) — DO NOT EDIT.
 * Every type-link emitted across the docs samples (B126-R3). The dangling-link guard
 * (site/scripts/api-link-guard.ts) validates each \`anchor\` against the /docs/api anchor
 * set, so a twoslash-emitted dead type-link fails the build (B126-R6). Plain data (D13).
 */

export interface SampleLink {
  readonly text: string;
  readonly anchor: string;
  readonly sample: string;
}

export const SAMPLE_LINKS: ReadonlyArray<SampleLink> = `;
  writeFileSync(LINKS_OUT, linksHeader + JSON.stringify(links, null, 2) + ";\n", "utf8");

  // eslint-disable-next-line no-console -- build-time progress log
  console.log(
    `build-samples: ${DOC_SAMPLES.length} samples → ${links.length} type-links (${SAMPLES_OUT})`,
  );
}

await main();
