/**
 * B109 (item 1) — build-time PLAIN Shiki highlight of the static guide code blocks.
 *
 * Build-time only (D13-exempt). Runs each entry in `src/lib/docs/code-blocks.ts` through a
 * warm Shiki highlighter with the SAME dual themes the rest of the site uses
 * (`site-paper` / `site-phosphor`, `defaultColor: false`) — but WITHOUT the twoslash
 * transformer, so the illustrative fragments (which reference schemas defined elsewhere) are
 * NOT type-checked and produce no type-links. Emits ONE generated, plain runtime-agnostic
 * module the client imports:
 *
 *  - `src/lib/docs/api/code-blocks.generated.ts` — `CODE_BLOCKS: Record<id, html>` (the
 *    pre-highlighted HTML `<CodeBlock>` renders).
 *
 * The warm highlighter is constructed ONCE and reused across every block (mirrors the B126
 * warm-highlighter discipline).
 */

import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync } from "node:fs";
import { createHighlighter } from "shiki";
import { DOC_CODE_BLOCKS } from "../src/lib/docs/code-blocks.js";
import { siteDark, siteLight } from "./shiki-theme.js";

const here = dirname(fileURLToPath(import.meta.url));
const siteRoot = resolve(here, "..");
const OUT = join(siteRoot, "src", "lib", "docs", "api", "code-blocks.generated.ts");

async function main(): Promise<void> {
  const highlighter = await createHighlighter({
    themes: [siteLight, siteDark],
    langs: ["ts", "bash"],
  });

  const htmlById: Record<string, string> = {};
  for (const block of DOC_CODE_BLOCKS) {
    htmlById[block.id] = highlighter.codeToHtml(block.code, {
      lang: block.lang ?? "ts",
      themes: { light: siteLight, dark: siteDark },
      defaultColor: false,
    });
  }

  const header = `/**
 * GENERATED by \`pnpm blocks:build\` (site/scripts/build-code-blocks.ts) — DO NOT EDIT.
 * Each value is the build-time Shiki-highlighted (dual-theme, NO twoslash / NO type-check)
 * HTML of a static guide code block (source of truth: src/lib/docs/code-blocks.ts). Plain
 * runtime-agnostic data (D13).
 */

export const CODE_BLOCKS: Record<string, string> = `;
  writeFileSync(OUT, header + JSON.stringify(htmlById, null, 2) + ";\n", "utf8");

  // eslint-disable-next-line no-console -- build-time progress log
  console.log(`build-code-blocks: ${DOC_CODE_BLOCKS.length} plain blocks → ${OUT}`);
}

await main();
