/**
 * Download English training corpora and emit five plain-TypeScript data files
 * under `packages/locale-en/src/data/` (the on-disk shape the barrel loader
 * in `packages/locale-en/src/data/index.ts` re-exports):
 *
 *   - first-names-male.ts
 *   - first-names-female.ts
 *   - last-names.ts
 *   - nouns.ts
 *   - adjectives.ts
 *
 * Each file exports a single `readonly string[]` constant. The consumer's
 * bundler does whatever compression it wants — the data layer ships as
 * runtime-agnostic source (no `node:fs`, `node:zlib`, brotli decompression).
 *
 * Sources (B48-R6, R4):
 *   - First names: SSA Baby Names — fetched from a GitHub mirror that ships
 *                  the SSA yearly text files as plain CSV (no zip required).
 *                  Original source: https://www.ssa.gov/oact/babynames (public
 *                  domain, US Social Security Administration). The mirror used
 *                  here is the `hadley/data-baby-names` SSA CSV (columns:
 *                  year,name,percent,sex). MIT-mirrored, content is public
 *                  domain.
 *   - Surnames:    US Census 2010 Surnames (public domain, US Census Bureau),
 *                  fetched from the `fivethirtyeight/data` GitHub mirror at
 *                  `most-common-name/surnames.csv` — this is the unmodified
 *                  Census 2010 file with header `name,rank,count,prop100k,
 *                  cum_prop100k,pctwhite,...`. **Filtered to top-10K by
 *                  frequency (the published `count` column)** per B48-R6.
 *   - Nouns/Adj:   dwyl/english-words `words_alpha.txt` (MIT) with the existing
 *                  4–12 length filter; adjectives are the suffix-heuristic subset
 *                  (B46 Q-S8 — non-blocking, deferred). 5_000 nouns, 3_000 adj.
 *
 * Usage: pnpm --filter @zod4-mock/locale-en fetch-data
 *
 * Network fallback: if a fetch fails, the script falls back to a previously
 * committed brotli blob at `src/data/blobs/en.br` if one exists (legacy 0.9.0
 * shape, decompressed at build time only); failing that, falls back to the
 * existing emitted `.ts` files' contents. A first-ever run with no network and
 * no fallback source exits non-zero.
 *
 * The brotli-decompression path here runs under `tsx` at build time and is
 * never shipped to consumers; the emitted product `.ts` files contain only
 * plain string arrays.
 */

import { brotliDecompressSync } from "node:zlib";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = join(__dirname, "../src/data");
const blobPath = join(dataDir, "blobs/en.br");

interface LegacyBlobShape {
  firstNamesMale: string[];
  firstNamesFemale: string[];
  lastNames: string[];
  nouns: string[];
  adjectives: string[];
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`);
  return res.text();
}

function loadLegacyBlob(): LegacyBlobShape | undefined {
  if (!existsSync(blobPath)) return undefined;
  const decoded = brotliDecompressSync(readFileSync(blobPath)).toString("utf-8");
  return JSON.parse(decoded) as LegacyBlobShape;
}

interface EmittedFile {
  filename: string;
  exportName: string;
  source: string;
  license: string;
}

function emitDataFile(
  meta: EmittedFile,
  entries: readonly string[],
): { path: string; bytes: number } {
  const header =
    `/**\n` +
    ` * Generated by packages/locale-en/scripts/fetch-data.ts.\n` +
    ` * Source: ${meta.source} (${meta.license}).\n` +
    ` * Entries: ${entries.length}.\n` +
    ` * Re-run \`pnpm --filter @zod4-mock/locale-en fetch-data\` to refresh.\n` +
    ` */\n\n`;
  const body = `export const ${meta.exportName}: readonly string[] = ${JSON.stringify(entries, null, 2)};\n`;
  const path = join(dataDir, meta.filename);
  const contents = header + body;
  writeFileSync(path, contents);
  return { path, bytes: Buffer.byteLength(contents, "utf-8") };
}

const legacy = loadLegacyBlob();

// ---------------------------------------------------------------------------
// 1. SSA Baby Names — github mirror of SSA yearly text files
// ---------------------------------------------------------------------------

let firstNamesMale: string[] | undefined;
let firstNamesFemale: string[] | undefined;

console.log("Fetching SSA Baby Names (mirror)…");
try {
  const csv = await fetchText(
    "https://raw.githubusercontent.com/hadley/data-baby-names/master/baby-names.csv",
  );
  const lines = csv
    .split("\n")
    .slice(1)
    .filter((l) => l.trim().length > 0);

  const males = new Set<string>();
  const females = new Set<string>();
  for (const line of lines) {
    const cols = line.split(",");
    if (cols.length < 4) continue;
    const rawName = cols[1]?.replace(/"/g, "").trim().toLowerCase() ?? "";
    const rawSex = cols[3]?.replace(/"/g, "").trim().toLowerCase() ?? "";
    if (!/^[a-z]+$/.test(rawName)) continue;
    if (rawSex === "boy") males.add(rawName);
    else if (rawSex === "girl") females.add(rawName);
  }

  if (males.size === 0 || females.size === 0) {
    throw new Error(`SSA mirror returned 0 names (males=${males.size}, females=${females.size})`);
  }
  firstNamesMale = [...males].sort();
  firstNamesFemale = [...females].sort();
  console.log(`  ✓ firstNamesMale (${firstNamesMale.length} names)`);
  console.log(`  ✓ firstNamesFemale (${firstNamesFemale.length} names)`);
} catch (e) {
  console.error("  ✗ SSA names failed:", (e as Error).message);
  console.error("    Falling back to previously committed data.");
}

// ---------------------------------------------------------------------------
// 2. US Census 2010 Surnames — top-10K by frequency (B48-R6)
// ---------------------------------------------------------------------------

let lastNames: string[] | undefined;

console.log("Fetching US Census 2010 Surnames (mirror)…");
try {
  const csv = await fetchText(
    "https://raw.githubusercontent.com/fivethirtyeight/data/master/most-common-name/surnames.csv",
  );
  type Row = { name: string; count: number };
  const rows: Row[] = csv
    .split("\n")
    .slice(1)
    .map((l): Row | null => {
      const cols = l.split(",");
      const name = cols[0]?.toLowerCase().trim();
      const count = Number(cols[2]);
      if (!name || !/^[a-z]+$/.test(name) || !Number.isFinite(count)) return null;
      return { name, count };
    })
    .filter((r): r is Row => r !== null);
  rows.sort((a, b) => b.count - a.count);
  lastNames = rows.slice(0, 10_000).map((r) => r.name);
  if (lastNames.length === 0) throw new Error("Census mirror returned 0 surnames");
  console.log(`  ✓ lastNames (${lastNames.length} names, top-10K filtered)`);
} catch (e) {
  console.error("  ✗ Census surnames failed:", (e as Error).message);
  console.error("    Falling back to previously committed data.");
}

// ---------------------------------------------------------------------------
// 3. English words (nouns + adjectives from dwyl/english-words)
// ---------------------------------------------------------------------------

let nouns: string[] | undefined;
let adjectives: string[] | undefined;

console.log("Fetching English word list…");
try {
  const wordList = await fetchText(
    "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt",
  );
  const words = wordList
    .split("\n")
    .map((w) => w.trim().toLowerCase())
    .filter((w) => /^[a-z]{4,12}$/.test(w));

  const adjSuffixes = [
    "ful",
    "less",
    "ous",
    "ive",
    "ible",
    "able",
    "al",
    "ic",
    "ish",
    "ary",
    "ory",
    "ent",
    "ant",
  ];
  const adj = words.filter((w) => adjSuffixes.some((s) => w.endsWith(s))).slice(0, 3000);
  const adjSet = new Set(adj);
  const nn = words.filter((w) => !adjSet.has(w)).slice(0, 5000);

  nouns = nn;
  adjectives = adj;
  console.log(`  ✓ nouns (${nn.length} words)`);
  console.log(`  ✓ adjectives (${adj.length} words)`);
} catch (e) {
  console.error("  ✗ Word list failed:", (e as Error).message);
  console.error("    Falling back to previously committed data.");
}

// ---------------------------------------------------------------------------
// 4. Resolve final lists (fetch result > legacy blob > existing .ts file)
// ---------------------------------------------------------------------------

async function loadExistingTs(filename: string, exportName: string): Promise<string[] | undefined> {
  const path = join(dataDir, filename);
  if (!existsSync(path)) return undefined;
  const mod = (await import(path)) as Record<string, unknown>;
  const value = mod[exportName];
  if (!Array.isArray(value)) return undefined;
  return value.filter((v): v is string => typeof v === "string");
}

const resolvedFirstNamesMale =
  firstNamesMale ??
  legacy?.firstNamesMale ??
  (await loadExistingTs("first-names-male.ts", "firstNamesMale"));
const resolvedFirstNamesFemale =
  firstNamesFemale ??
  legacy?.firstNamesFemale ??
  (await loadExistingTs("first-names-female.ts", "firstNamesFemale"));
const resolvedLastNames =
  lastNames ?? legacy?.lastNames ?? (await loadExistingTs("last-names.ts", "lastNames"));
const resolvedNouns = nouns ?? legacy?.nouns ?? (await loadExistingTs("nouns.ts", "nouns"));
const resolvedAdjectives =
  adjectives ?? legacy?.adjectives ?? (await loadExistingTs("adjectives.ts", "adjectives"));

if (
  !resolvedFirstNamesMale ||
  !resolvedFirstNamesFemale ||
  !resolvedLastNames ||
  !resolvedNouns ||
  !resolvedAdjectives
) {
  console.error(
    "\nFATAL: at least one corpus failed to fetch and no fallback is available " +
      "(no committed brotli blob, no existing .ts file). Re-run with network access.",
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------
// 5. Emit five plain-TypeScript files
// ---------------------------------------------------------------------------

const emitted = [
  emitDataFile(
    {
      filename: "first-names-male.ts",
      exportName: "firstNamesMale",
      source:
        "SSA Baby Names (https://www.ssa.gov/oact/babynames) via hadley/data-baby-names mirror",
      license: "public domain; mirror MIT",
    },
    resolvedFirstNamesMale,
  ),
  emitDataFile(
    {
      filename: "first-names-female.ts",
      exportName: "firstNamesFemale",
      source:
        "SSA Baby Names (https://www.ssa.gov/oact/babynames) via hadley/data-baby-names mirror",
      license: "public domain; mirror MIT",
    },
    resolvedFirstNamesFemale,
  ),
  emitDataFile(
    {
      filename: "last-names.ts",
      exportName: "lastNames",
      source: "US Census 2010 Surnames via fivethirtyeight/data mirror (top-10K by frequency)",
      license: "public domain; mirror MIT",
    },
    resolvedLastNames,
  ),
  emitDataFile(
    {
      filename: "nouns.ts",
      exportName: "nouns",
      source: "dwyl/english-words words_alpha.txt (4–12 length filter, 5_000 entries)",
      license: "Unlicense",
    },
    resolvedNouns,
  ),
  emitDataFile(
    {
      filename: "adjectives.ts",
      exportName: "adjectives",
      source: "dwyl/english-words words_alpha.txt (suffix-heuristic, 3_000 entries)",
      license: "Unlicense",
    },
    resolvedAdjectives,
  ),
];

const totalBytes = emitted.reduce((sum, e) => sum + e.bytes, 0);
console.log(`\n✓ Wrote ${emitted.length} files (${totalBytes} bytes total):`);
for (const e of emitted) {
  console.log(`  ${e.path}  (${e.bytes} bytes)`);
}
console.log(`\n  firstNamesMale:   ${resolvedFirstNamesMale.length}`);
console.log(`  firstNamesFemale: ${resolvedFirstNamesFemale.length}`);
console.log(`  lastNames:        ${resolvedLastNames.length}`);
console.log(`  nouns:            ${resolvedNouns.length}`);
console.log(`  adjectives:       ${resolvedAdjectives.length}`);
