/**
 * Download Dutch training corpora and emit five plain-TypeScript data files
 * under `packages/locale-nl/src/data/` (the on-disk shape the barrel loader
 * in `packages/locale-nl/src/data/index.ts` re-exports):
 *
 *   - first-names-male.ts
 *   - first-names-female.ts
 *   - last-names.ts
 *   - nouns.ts
 *   - adjectives.ts
 *
 * Each file exports a single `readonly string[]` constant. The consumer's
 * bundler does whatever compression it wants — the data layer ships as
 * runtime-agnostic source (no `node:fs`, `node:zlib`, brotli decompression).
 *
 * Sources (B48-R5, R4):
 *   - First names: open-nl-data/dutch-names-dataset (MIT, B46 Q-S1).
 *     Fetched from a GitHub raw URL. Mannen > 100 / Vrouwen > 100 thresholds
 *     select the Dutch-core corpus and discard low-frequency entries.
 *   - Surnames:    **Best-effort — see NOTE below.** The B48-R5 spec says
 *     surnames MUST be refetched from CBS (Statistics Netherlands) or Meertens
 *     directly. CBS does NOT publish a bulk Dutch-surname dataset through
 *     `opendata.cbs.nl` (their published surname work covers per-name frequency
 *     lookups but not a bulk top-N download); Meertens' NFB ships data as a
 *     paginated HTML browser UI, not as a bulk JSON/CSV download. Falls back
 *     to the previously-emitted slice (2007 Dutch top-1000 surname survey,
 *     Meertens NFB-derived). A CBS/Meertens bulk refetch is filed as a
 *     follow-up enhancement.
 *   - Nouns/Adj:   OpenTaal opentaal-wordlist (BSD/GPL — Dutch open word
 *     list). Heuristic adjective filter (suffix-based) carried over.
 *
 * Usage: pnpm --filter @zod4-mock/locale-nl fetch-data
 *
 * Network fallback: if a fetch fails, the script falls back to a previously
 * committed brotli blob at `src/data/blobs/nl.br` if one exists (legacy 0.9.0
 * shape, decompressed at build time only); failing that, falls back to the
 * existing emitted `.ts` files' contents. A first-ever run with no network
 * and no fallback source exits non-zero.
 *
 * The brotli-decompression path here runs under `tsx` at build time and is
 * never shipped to consumers; the emitted product `.ts` files contain only
 * plain string arrays.
 */

import { brotliDecompressSync } from "node:zlib";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = join(__dirname, "../src/data");
const blobPath = join(dataDir, "blobs/nl.br");

interface LegacyBlobShape {
  firstNamesMale: string[];
  firstNamesFemale: string[];
  lastNames: string[];
  nouns: string[];
  adjectives: string[];
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`);
  return res.text();
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`);
  return res.json() as Promise<T>;
}

function loadLegacyBlob(): LegacyBlobShape | undefined {
  if (!existsSync(blobPath)) return undefined;
  const decoded = brotliDecompressSync(readFileSync(blobPath)).toString("utf-8");
  return JSON.parse(decoded) as LegacyBlobShape;
}

interface EmittedFile {
  filename: string;
  exportName: string;
  source: string;
  license: string;
}

function emitDataFile(
  meta: EmittedFile,
  entries: readonly string[],
): { path: string; bytes: number } {
  const header =
    `/**\n` +
    ` * Generated by packages/locale-nl/scripts/fetch-data.ts.\n` +
    ` * Source: ${meta.source} (${meta.license}).\n` +
    ` * Entries: ${entries.length}.\n` +
    ` * Re-run \`pnpm --filter @zod4-mock/locale-nl fetch-data\` to refresh.\n` +
    ` */\n\n`;
  const body = `export const ${meta.exportName}: readonly string[] = ${JSON.stringify(entries, null, 2)};\n`;
  const path = join(dataDir, meta.filename);
  const contents = header + body;
  writeFileSync(path, contents);
  return { path, bytes: Buffer.byteLength(contents, "utf-8") };
}

const legacy = loadLegacyBlob();

// ---------------------------------------------------------------------------
// 1. Dutch first names — open-nl-data/dutch-names-dataset (MIT)
// ---------------------------------------------------------------------------

let firstNamesMale: string[] | undefined;
let firstNamesFemale: string[] | undefined;

console.log("Fetching Dutch first names (open-nl-data)…");
try {
  type NameEntry = { Voornaam: string; Mannen: number; Vrouwen: number };
  const candidates = [
    "https://raw.githubusercontent.com/open-nl-data/dutch-names-dataset/main/firstnames.json",
    "https://raw.githubusercontent.com/open-nl-data/dutch-names-dataset/master/firstnames.json",
    "https://raw.githubusercontent.com/open-nl-data/dutch-names-dataset/main/data/firstnames.json",
  ];
  let names: NameEntry[] | undefined;
  let lastErr: Error | undefined;
  for (const url of candidates) {
    try {
      names = await fetchJson<NameEntry[]>(url);
      console.log(`  source: ${url}`);
      break;
    } catch (e) {
      lastErr = e as Error;
    }
  }
  if (!names) throw lastErr ?? new Error("all open-nl-data candidates failed");

  const cleanList = (raw: string[]): string[] =>
    [
      ...new Set(
        raw
          .map((n) => n.trim())
          .filter((n) => /^[A-Z][a-z]+$/.test(n))
          .map((n) => n.charAt(0).toUpperCase() + n.slice(1).toLowerCase()),
      ),
    ].sort();

  firstNamesMale = cleanList(names.filter((n) => n.Mannen > 100).map((n) => n.Voornaam));
  firstNamesFemale = cleanList(names.filter((n) => n.Vrouwen > 100).map((n) => n.Voornaam));
  if (firstNamesMale.length === 0 || firstNamesFemale.length === 0) {
    throw new Error("Dutch first-name source returned an empty list after filter");
  }
  console.log(`  ✓ firstNamesMale (${firstNamesMale.length} names)`);
  console.log(`  ✓ firstNamesFemale (${firstNamesFemale.length} names)`);
} catch (e) {
  console.error("  ✗ Dutch first names failed:", (e as Error).message);
  console.error("    Falling back to previously committed data.");
}

// ---------------------------------------------------------------------------
// 2. Dutch surnames — best-effort; see header NOTE.
// ---------------------------------------------------------------------------

const lastNames: string[] | undefined = undefined;

console.log("Fetching Dutch surnames…");
console.log("  ⓘ No bulk CBS/Meertens endpoint — using previously committed data.");

// ---------------------------------------------------------------------------
// 3. Dutch nouns + adjectives — OpenTaal wordlist
// ---------------------------------------------------------------------------

let nouns: string[] | undefined;
let adjectives: string[] | undefined;

console.log("Fetching OpenTaal word list…");
try {
  const wordList = await fetchText(
    "https://raw.githubusercontent.com/OpenTaal/opentaal-wordlist/master/wordlist.txt",
  );
  const words = wordList
    .split("\n")
    .map((w) => w.trim().toLowerCase())
    .filter((w) => /^[a-z]{4,14}$/.test(w));

  const adjSuffixes = ["lijk", "isch", "ig", "baar", "loos", "rijk", "vol", "zaam"];
  const adj = words.filter((w) => adjSuffixes.some((s) => w.endsWith(s))).slice(0, 2000);
  const adjSet = new Set(adj);
  const nn = words.filter((w) => !adjSet.has(w)).slice(0, 5000);

  if (nn.length === 0 || adj.length === 0) {
    throw new Error(`OpenTaal returned empty buckets (nouns=${nn.length}, adj=${adj.length})`);
  }
  nouns = nn;
  adjectives = adj;
  console.log(`  ✓ nouns (${nn.length} words)`);
  console.log(`  ✓ adjectives (${adj.length} words)`);
} catch (e) {
  console.error("  ✗ OpenTaal word list failed:", (e as Error).message);
  console.error("    Falling back to previously committed data.");
}

// ---------------------------------------------------------------------------
// 4. Resolve final lists (fetch result > legacy blob > existing .ts file)
// ---------------------------------------------------------------------------

async function loadExistingTs(filename: string, exportName: string): Promise<string[] | undefined> {
  const path = join(dataDir, filename);
  if (!existsSync(path)) return undefined;
  const mod = (await import(path)) as Record<string, unknown>;
  const value = mod[exportName];
  if (!Array.isArray(value)) return undefined;
  return value.filter((v): v is string => typeof v === "string");
}

const resolvedFirstNamesMale =
  firstNamesMale ??
  legacy?.firstNamesMale ??
  (await loadExistingTs("first-names-male.ts", "firstNamesMale"));
const resolvedFirstNamesFemale =
  firstNamesFemale ??
  legacy?.firstNamesFemale ??
  (await loadExistingTs("first-names-female.ts", "firstNamesFemale"));
const resolvedLastNames =
  lastNames ?? legacy?.lastNames ?? (await loadExistingTs("last-names.ts", "lastNames"));
const resolvedNouns = nouns ?? legacy?.nouns ?? (await loadExistingTs("nouns.ts", "nouns"));
const resolvedAdjectives =
  adjectives ?? legacy?.adjectives ?? (await loadExistingTs("adjectives.ts", "adjectives"));

if (
  !resolvedFirstNamesMale ||
  !resolvedFirstNamesFemale ||
  !resolvedLastNames ||
  !resolvedNouns ||
  !resolvedAdjectives
) {
  console.error(
    "\nFATAL: at least one corpus failed to fetch and no fallback is available " +
      "(no committed brotli blob, no existing .ts file). Re-run with network access.",
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------
// 5. Emit five plain-TypeScript files
// ---------------------------------------------------------------------------

const emitted = [
  emitDataFile(
    {
      filename: "first-names-male.ts",
      exportName: "firstNamesMale",
      source: "open-nl-data/dutch-names-dataset (Mannen>100 threshold)",
      license: "MIT",
    },
    resolvedFirstNamesMale,
  ),
  emitDataFile(
    {
      filename: "first-names-female.ts",
      exportName: "firstNamesFemale",
      source: "open-nl-data/dutch-names-dataset (Vrouwen>100 threshold)",
      license: "MIT",
    },
    resolvedFirstNamesFemale,
  ),
  emitDataFile(
    {
      filename: "last-names.ts",
      exportName: "lastNames",
      source: "Phase 1 migration from prior locale-names Dutch slice (2007 NL top-1000 survey)",
      license: "Meertens-NFB-derived; redistribution under fair-use",
    },
    resolvedLastNames,
  ),
  emitDataFile(
    {
      filename: "nouns.ts",
      exportName: "nouns",
      source: "OpenTaal opentaal-wordlist (4–14 length filter, 5_000 entries)",
      license: "BSD / GPL",
    },
    resolvedNouns,
  ),
  emitDataFile(
    {
      filename: "adjectives.ts",
      exportName: "adjectives",
      source: "OpenTaal opentaal-wordlist (suffix-heuristic, 2_000 entries)",
      license: "BSD / GPL",
    },
    resolvedAdjectives,
  ),
];

const totalBytes = emitted.reduce((sum, e) => sum + e.bytes, 0);
console.log(`\n✓ Wrote ${emitted.length} files (${totalBytes} bytes total):`);
for (const e of emitted) {
  console.log(`  ${e.path}  (${e.bytes} bytes)`);
}
console.log(`\n  firstNamesMale:   ${resolvedFirstNamesMale.length}`);
console.log(`  firstNamesFemale: ${resolvedFirstNamesFemale.length}`);
console.log(`  lastNames:        ${resolvedLastNames.length}`);
console.log(`  nouns:            ${resolvedNouns.length}`);
console.log(`  adjectives:       ${resolvedAdjectives.length}`);
