/**
 * Regression test for the explicit-source derived field-seed collapse.
 *
 * Bug: `generateWithSourceOverride` hardcoded `sourceIndex: 0` when calling
 * `generateDerivedRecord`, so every `world.generate(DerivedSchema, { source })`
 * built the same record id `dreg<regId>#0` and therefore the same field PRNG
 * seed. All field-PRNG-derived fields (anything NOT pulled straight off
 * `ctx.source`) were IDENTICAL across distinct sources — only source-derived
 * fields like `ctx.source.id` varied.
 *
 * Fix: seed the field PRNG from the source IDENTITY
 * (`sourceFieldIndex(computeSourceIdentity(...))`) so distinct sources get
 * distinct field seeds, while staying value-keyed (order-independent, D4/D10)
 * and preserving the B8 upsert short-circuit.
 *
 * Probe field: `UserProfileSchema.bio` is generated by the field PRNG (it has
 * no matcher and is not pulled from the source), so it is identical across
 * sources iff the seeds collapse.
 */

import { describe, it, expect } from "vitest";
import { z } from "zod";
import { createWorld } from "../../../src/index.js";

const UserSchema = z.object({
  id: z.uuid(),
  email: z.string(),
});

// `bio` comes from the field PRNG; `userId` is pulled from the source.
const UserProfileSchema = z.object({
  userId: z.uuid(),
  bio: z.string(),
  nickname: z.string(),
});

// Reference-identity variant (no sourceKey): distinct refs => distinct records.
function makeWorld(seed = 42) {
  return createWorld({ seed })
    .withSchema(UserSchema)
    .withSchema(UserProfileSchema, {
      from: UserSchema,
      matchers: { userId: (ctx) => ctx.source.id },
    });
}

// sourceKey variant: identity resolves via `id`.
function makeWorldWithKey(seed = 42) {
  return createWorld({ seed })
    .withSchema(UserSchema)
    .withSchema(UserProfileSchema, {
      from: UserSchema,
      sourceKey: "id",
      matchers: { userId: (ctx) => ctx.source.id },
    });
}

describe("derived explicit-source field seeding — regression", () => {
  it("distinct sources produce distinct field-PRNG fields (not just source-pulled fields)", () => {
    const world = makeWorld();
    world.populate(UserSchema, 3);
    const [u1, u2, u3] = world.registry.all(UserSchema) as Array<{ id: string }>;

    const p1 = world.generate(UserProfileSchema, { source: u1 });
    const p2 = world.generate(UserProfileSchema, { source: u2 });
    const p3 = world.generate(UserProfileSchema, { source: u3 });

    // Source-pulled field varies (this varied even WITH the bug).
    expect(new Set([p1.userId, p2.userId, p3.userId]).size).toBe(3);

    // Field-PRNG fields must ALSO vary — the bug made these identical.
    expect(new Set([p1.bio, p2.bio, p3.bio]).size).toBe(3);
    expect(new Set([p1.nickname, p2.nickname, p3.nickname]).size).toBe(3);
  });

  it("is deterministic: same seed + same source identity -> same record across worlds", () => {
    const wA = makeWorld(7);
    wA.populate(UserSchema, 2);
    const aUsers = wA.registry.all(UserSchema);

    const wB = makeWorld(7);
    wB.populate(UserSchema, 2);
    const bUsers = wB.registry.all(UserSchema);

    // Same seed => same generated users => same source identities.
    expect(aUsers).toEqual(bUsers);

    const a = wA.generate(UserProfileSchema, { source: aUsers[1] });
    const b = wB.generate(UserProfileSchema, { source: bUsers[1] });

    expect(a).toEqual(b);
  });

  it("order-independent: the bio for a given source does not depend on call order", () => {
    const w1 = makeWorld(99);
    w1.populate(UserSchema, 3);
    const u1 = w1.registry.all(UserSchema);
    // Generate for the THIRD user first.
    const third1 = w1.generate(UserProfileSchema, { source: u1[2] });

    const w2 = makeWorld(99);
    w2.populate(UserSchema, 3);
    const u2 = w2.registry.all(UserSchema);
    // Generate first and second before the third.
    w2.generate(UserProfileSchema, { source: u2[0] });
    w2.generate(UserProfileSchema, { source: u2[1] });
    const third2 = w2.generate(UserProfileSchema, { source: u2[2] });

    // Same source identity -> same record regardless of when it was generated.
    expect(third1).toEqual(third2);
  });

  it("sourceKey look-alikes (same id) share the same field seed -> identical record", () => {
    const world = makeWorldWithKey();
    world.populate(UserSchema, 1);
    const user = world.registry.pick(UserSchema) as { id: string };

    const a = world.generate(UserProfileSchema, { source: user });

    // Different reference, same `id` — resolves to the same identity.
    const lookAlike = { ...user };
    const b = world.generate(UserProfileSchema, { source: lookAlike });

    // Upsert short-circuit returns the same instance.
    expect(a).toBe(b);
    expect(world.registry.count(UserProfileSchema)).toBe(1);
  });
});
