/**
 * B102-R6/R7/R8/R9 — API docs generator.
 *
 * One extraction (`scripts/docs/extract.ts`), two render targets:
 *   1. the site's generated manifest data file
 *      (`site/src/lib/docs/api/manifest.generated.ts`), consumed by
 *      `site/src/routes/docs/api/+page.svelte`; and
 *   2. `docs/api-reference.md`, rendered from a fixed template.
 *
 * Modes:
 *   - write (default): emits both files. Idempotent — re-running with no
 *     TSDoc/type/curation change produces byte-identical output.
 *   - `--check`: renders both targets in memory and compares to the on-disk
 *     files. On any drift it prints a per-target diff that names the drifted
 *     symbol(s) and exits non-zero; in sync it exits 0 and writes nothing.
 *
 * Optional `--src` / `--out` overrides are accepted for test harnesses; absent,
 * the repo-root paths are used. Build-time only (D13-exempt), no `any` (D1),
 * runs under `tsx`.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildManifest, type ManifestSymbol } from "./docs/extract.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..");
const API_REFERENCE = join(REPO_ROOT, "docs", "api-reference.md");
const SITE_MANIFEST = join(REPO_ROOT, "site", "src", "lib", "docs", "api", "manifest.generated.ts");

interface CliArgs {
  check: boolean;
}

function parseArgs(argv: ReadonlyArray<string>): CliArgs {
  return { check: argv.includes("--check") };
}

// ── Rendering ────────────────────────────────────────────────────────────────

function mdEscape(text: string): string {
  return text
    .replace(/\|/g, "\\|")
    .replace(/\r?\n+/g, " ")
    .trim();
}

/** Render `docs/api-reference.md` from the manifest. */
function renderMarkdown(manifest: ReadonlyArray<ManifestSymbol>): string {
  const lines: string[] = [];
  lines.push("# API Reference");
  lines.push("");
  lines.push(
    "> Generated from the TSDoc and types of the `src/` public exports by " +
      "`pnpm docs:generate`. Do not edit by hand — update the exported symbol's " +
      "TSDoc in `src/` and regenerate. Parity is verified by `pnpm docs:check`.",
  );
  lines.push("");

  // Exports overview table — one row per manifest symbol.
  lines.push("## Exports overview");
  lines.push("");
  lines.push("| Export | Kind | Summary |");
  lines.push("| ------ | ---- | ------- |");
  for (const sym of manifest) {
    const summary = mdEscape(firstSentence(sym.description));
    lines.push(`| \`${sym.name}\` | ${sym.kind} | ${summary} |`);
  }
  lines.push("");

  // Per-symbol sections.
  for (const sym of manifest) {
    lines.push(`## ${sym.name}`);
    lines.push("");
    lines.push("```ts");
    lines.push(sym.signature);
    lines.push("```");
    lines.push("");
    if (sym.description.length > 0) {
      lines.push(sym.description);
      lines.push("");
    }
    if (sym.parameters && sym.parameters.length > 0) {
      lines.push("**Parameters**");
      lines.push("");
      lines.push("| Name | Type | Default | Description |");
      lines.push("| ---- | ---- | ------- | ----------- |");
      for (const p of sym.parameters) {
        lines.push(
          `| \`${p.name}\` | \`${mdEscape(p.type)}\` | ${
            p.default ? `\`${mdEscape(p.default)}\`` : "—"
          } | ${mdEscape(p.description)} |`,
        );
      }
      lines.push("");
    }
    for (const ex of sym.examples) {
      lines.push("**Example**");
      lines.push("");
      lines.push(ex.trim());
      lines.push("");
    }
    if (sym.seeAlso.length > 0) {
      lines.push(`**See also:** ${sym.seeAlso.map((s) => mdEscape(s)).join(", ")}`);
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function firstSentence(text: string): string {
  const trimmed = text.trim();
  const m = trimmed.match(/^(.*?[.!?])(\s|$)/s);
  return (m?.[1] ?? trimmed).replace(/\s+/g, " ").trim();
}

/** Render the site's generated manifest data module. */
function renderSiteManifest(manifest: ReadonlyArray<ManifestSymbol>): string {
  const header = [
    "/**",
    " * GENERATED by `pnpm docs:generate` — DO NOT EDIT.",
    " *",
    " * Source of truth: the TSDoc + types of the `src/` public exports",
    " * (`scripts/docs/extract.ts`) plus the curation layer",
    " * (`scripts/docs/curation.ts`). Regenerate via `pnpm docs:generate`;",
    " * parity is verified by `pnpm docs:check`. Runtime-agnostic plain data (D13).",
    " */",
    "",
    "export interface ApiParameterRow {",
    "\treadonly name: string;",
    "\treadonly type: string;",
    "\treadonly default?: string;",
    "\treadonly description: string;",
    "}",
    "",
    "export interface ApiSymbol {",
    "\treadonly name: string;",
    '\treadonly kind: "function" | "type" | "namespace" | "object";',
    "\treadonly group: string;",
    "\treadonly signature: string;",
    "\treadonly description: string;",
    "\treadonly examples: ReadonlyArray<string>;",
    "\treadonly since: string;",
    "\treadonly seeAlso: ReadonlyArray<string>;",
    "\treadonly parameters?: ReadonlyArray<ApiParameterRow>;",
    "}",
    "",
    "export const API_MANIFEST: ReadonlyArray<ApiSymbol> = ",
  ].join("\n");
  const body = JSON.stringify(manifest, null, 2);
  return `${header}${body} as const;\n`;
}

// ── Modes ────────────────────────────────────────────────────────────────────

interface Target {
  readonly label: string;
  readonly path: string;
  readonly content: string;
}

function diffSymbols(expected: string, actual: string): string[] {
  // Heuristic: report which `## <Name>` sections differ between expected/actual.
  const expSections = sectionMap(expected);
  const actSections = sectionMap(actual);
  const names = new Set<string>([...expSections.keys(), ...actSections.keys()]);
  const drifted: string[] = [];
  for (const name of names) {
    if (expSections.get(name) !== actSections.get(name)) drifted.push(name);
  }
  return drifted;
}

function sectionMap(md: string): Map<string, string> {
  const map = new Map<string, string>();
  const lines = md.split("\n");
  let cur: string | null = null;
  let buf: string[] = [];
  const flush = (): void => {
    if (cur !== null) map.set(cur, buf.join("\n"));
  };
  for (const line of lines) {
    const m = line.match(/^##\s+(.+)$/);
    if (m) {
      flush();
      cur = m[1]!.trim();
      buf = [];
    } else if (cur !== null) {
      buf.push(line);
    }
  }
  flush();
  return map;
}

function firstDiffLine(expected: string, actual: string): string {
  const e = expected.split("\n");
  const a = actual.split("\n");
  const n = Math.max(e.length, a.length);
  for (let i = 0; i < n; i++) {
    if (e[i] !== a[i]) {
      return `  line ${i + 1}:\n    expected: ${e[i] ?? "<eof>"}\n    on disk:  ${a[i] ?? "<eof>"}`;
    }
  }
  return "  (whole-file mismatch)";
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const manifest = buildManifest();

  const targets: ReadonlyArray<Target> = [
    { label: "docs/api-reference.md", path: API_REFERENCE, content: renderMarkdown(manifest) },
    {
      label: "site manifest",
      path: SITE_MANIFEST,
      content: renderSiteManifest(manifest),
    },
  ];

  if (!args.check) {
    for (const t of targets) {
      mkdirSync(dirname(t.path), { recursive: true });
      writeFileSync(t.path, t.content, "utf8");
    }
    process.stdout.write(`docs:generate wrote ${targets.length} file(s).\n`);
    return;
  }

  // --check: compare to on-disk, report drift, exit non-zero on mismatch.
  let drift = false;
  for (const t of targets) {
    let onDisk = "";
    try {
      onDisk = readFileSync(t.path, "utf8");
    } catch {
      onDisk = "";
    }
    if (onDisk !== t.content) {
      drift = true;
      const drifted = diffSymbols(t.content, onDisk);
      process.stderr.write(`docs:check — drift in ${t.label}\n`);
      if (drifted.length > 0) {
        process.stderr.write(`  drifted symbol(s): ${drifted.join(", ")}\n`);
      }
      process.stderr.write(`${firstDiffLine(t.content, onDisk)}\n`);
      process.stderr.write(`  run \`pnpm docs:generate\` to regenerate.\n`);
    }
  }
  if (drift) {
    process.exit(1);
  }
  process.stdout.write("docs:check — generated docs are in sync.\n");
}

main();
