/**
 * @module world
 * The central context for one data-generation session.
 *
 * ## Usage
 *
 * ```ts
 * import { createWorld } from './world.js'
 * import { defineSubjectType } from './subject.js'
 *
 * const PersonSubject = defineSubjectType('person', PersonSchema)
 *
 * const world = createWorld({ seed: 42 })
 *   .withSubject(PersonSubject)
 *   .withSchema(PersonApiSchema, 'person', {
 *     firstName: (s) => s.firstName,
 *   })
 *
 * const people = world.generate(z.array(PersonApiSchema).min(5).max(20))
 * ```
 *
 * ## Determinism
 *
 * Every value generated by a world is fully deterministic given the seed.
 * The same seed + same call order always produces the same output, across
 * runs and across machines.
 *
 * ## Generation pipeline
 *
 * For each field of a schema, values are resolved in this order:
 * 1. Matchers registered via `withSchema`
 * 2. Key-based generators (field name heuristics)
 * 3. Schema-based generator (Zod type introspection)
 * 4. `options.overrides` deep merge
 * 5. `options.transform` function
 */

import type { ZodTypeAny, input } from 'zod'
import type {
  World,
  WorldOptions,
  AnySubjectType,
  AnySubjectInstance,
  SubjectData,
  Matchers,
  GenerateOptions,
  Registry,
} from './types.js'
import { SubjectRegistry } from './registry.js'
import { createPrng } from './prng.js'

export class WorldImpl implements World {
  private readonly prng: ReturnType<typeof createPrng>
  readonly registry: Registry

  /** Registered subject type definitions, keyed by type name. */
  private readonly subjectTypes: Map<string, AnySubjectType> = new Map()

  /**
   * Schema registrations: each entry binds a Zod schema to one or more subject
   * types, along with optional matcher functions.
   */
  private readonly schemaRegistrations: Array<{
    schema: ZodTypeAny
    subjectTypes: string[]
    matchers: Matchers<ZodTypeAny, unknown>
  }> = []

  /** Counter per subject type for generating stable sequential IDs. */
  private readonly subjectCounters: Map<string, number> = new Map()

  constructor(private readonly options: WorldOptions) {
    this.prng = createPrng(options.seed)
    this.registry = new SubjectRegistry(this.prng.fork('registry'))
  }

  withSubject(subjectType: AnySubjectType): this {
    throw new Error('not implemented')
  }

  withSchema<TSchema extends ZodTypeAny, TSubjectType extends AnySubjectType>(
    schema: TSchema,
    subjectType: TSubjectType,
    matchers?: Matchers<TSchema, SubjectData<TSubjectType>>,
  ): this
  withSchema<TSchema extends ZodTypeAny>(
    schema: TSchema,
    subjectTypes: string | string[],
    matchers?: Matchers<TSchema, unknown>,
  ): this
  withSchema(
    _schema: ZodTypeAny,
    _subjectTypes: AnySubjectType | string | string[],
    _matchers?: unknown,
  ): this {
    throw new Error('not implemented')
  }

  generate<TSchema extends ZodTypeAny>(
    schema: TSchema,
    options?: GenerateOptions<input<TSchema>>,
  ): input<TSchema> {
    throw new Error('not implemented')
  }

  subject(type: string): AnySubjectInstance {
    throw new Error('not implemented')
  }
}

/**
 * Create a new world with the given options.
 *
 * Register subject types and app schemas declaratively before calling
 * `generate`.  All generation is lazy and deterministic.
 *
 * @example
 * ```ts
 * const world = createWorld({ seed: 42 })
 *   .withSubject(PersonSubject)
 *   .withSchema(PersonApiSchema, 'person', {
 *     email: (s) => `${s.firstName[0]}.${s.lastName}@example.nl`.toLowerCase(),
 *   })
 * ```
 */
export function createWorld(options: WorldOptions): World {
  return new WorldImpl(options)
}
