/**
 * @module world
 * The central context for one data-generation session.
 *
 * ## Usage
 *
 * ```ts
 * import { createWorld } from './world.js'
 * import { defineSubjectType } from './subject.js'
 *
 * const PersonSubject = defineSubjectType('person', PersonSchema)
 *
 * const world = createWorld({ seed: 42 })
 *   .withSubject(PersonSubject)
 *   .withSchema(PersonApiSchema, 'person', {
 *     firstName: (s) => s.firstName,
 *   })
 *
 * const people = world.generate(z.array(PersonApiSchema).min(5).max(20))
 * ```
 *
 * ## Determinism
 *
 * Every value generated by a world is fully deterministic given the seed.
 * The same seed + same call order always produces the same output, across
 * runs and across machines.
 *
 * ## Generation pipeline
 *
 * For each field of a schema, values are resolved in this order:
 * 1. Matchers registered via `withSchema`
 * 2. Key-based generators (field name heuristics)
 * 3. Schema-based generator (Zod type introspection)
 * 4. `options.overrides` deep merge
 * 5. `options.transform` function
 */

import type { ZodTypeAny, input } from "zod";
import type {
  World,
  WorldOptions,
  AnySubjectType,
  AnySubjectInstance,
  SubjectData,
  Matchers,
  MatcherFn,
  GenerateOptions,
  Registry,
  GeneratorContext,
  SubjectMatcherArg,
  KeyGenerator,
  SchemaKeyMap,
} from "./types.js";
import { SubjectRegistry } from "./registry.js";
import { createPrng, fieldSeed } from "./prng.js";
import { generateFromSchema } from "./generators/schema/index.js";
import { generateFromKey } from "./generators/key-based.js";

// ---------------------------------------------------------------------------
// Internal types
// ---------------------------------------------------------------------------

interface SchemaReg {
  schema: ZodTypeAny;
  subjectTypes: string[];
  matchers: Record<string, MatcherFn<unknown, unknown>>;
}

interface SubjectRegPair {
  instance: AnySubjectInstance;
  reg: SchemaReg;
}

// ---------------------------------------------------------------------------
// Zod v4 def helpers
// ---------------------------------------------------------------------------

interface ZodDefShape {
  type: string;
  element?: ZodTypeAny;
  innerType?: ZodTypeAny;
  shape?: Record<string, ZodTypeAny>;
  checks?: Array<{ check: string; minimum?: number; maximum?: number; length?: number }>;
}

function getZodDef(schema: ZodTypeAny): ZodDefShape {
  return (schema as unknown as { _zod: { def: ZodDefShape } })._zod.def;
}

// ---------------------------------------------------------------------------
// Deep merge helper (non-array, non-null objects only)
// ---------------------------------------------------------------------------

function deepMerge(target: unknown, source: unknown): unknown {
  if (
    typeof source !== "object" ||
    source === null ||
    Array.isArray(source) ||
    typeof target !== "object" ||
    target === null ||
    Array.isArray(target)
  ) {
    return source;
  }
  const result = { ...(target as Record<string, unknown>) };
  for (const [k, sv] of Object.entries(source as Record<string, unknown>)) {
    if (sv !== undefined) {
      result[k] = deepMerge(result[k], sv);
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// Minimum array-length resolver (reads only min/length_equals constraints)
// ---------------------------------------------------------------------------

interface CheckDef {
  check: string;
  minimum?: number;
  maximum?: number;
  length?: number;
  value?: number;
  inclusive?: boolean;
  format?: string;
}

/** Extract inner `_zod.def` objects from a schema's checks array. */
function getCheckDefs(schema: ZodTypeAny): CheckDef[] {
  const raw = (getZodDef(schema).checks ?? []) as unknown as Array<{ _zod: { def: CheckDef } }>;
  return raw.map((c) => c._zod.def);
}

function resolveMinRequired(schema: ZodTypeAny, defaultMin: number): number {
  let min = defaultMin;
  for (const c of getCheckDefs(schema)) {
    if (c.check === "length_equals") return c.length!;
    if (c.check === "min_length" && c.minimum !== undefined) {
      min = Math.max(min, c.minimum);
    }
  }
  return min;
}

// ---------------------------------------------------------------------------
// WorldImpl
// ---------------------------------------------------------------------------

export class WorldImpl implements World {
  private readonly prng: ReturnType<typeof createPrng>;
  readonly registry: Registry;

  /** Registered subject type definitions, keyed by type name. */
  private readonly subjectTypes: Map<string, AnySubjectType> = new Map();

  /** Schema registrations: each entry binds a Zod schema to subject type(s) + matchers. */
  private readonly schemaRegs: SchemaReg[] = [];

  /** Counter per subject type for stable sequential IDs (`person#1`, `person#2`, …). */
  private readonly subjectCounters: Map<string, number> = new Map();

  /** All created subject instances, in creation order. */
  private readonly allInstances: AnySubjectInstance[] = [];

  /** Incremented on every `generate()` call; used to cycle through subject pairs. */
  private generationCounter = 0;

  /** Custom key-based generators, keyed by lowercased field name. */
  private readonly customKeyGenerators: Map<string, KeyGenerator> = new Map();

  /** Per-schema key maps registered via withKeyMap, keyed by schema identity. */
  private readonly schemaKeyMaps: Map<
    ZodTypeAny,
    Record<string, (ctx: GeneratorContext) => unknown>
  > = new Map();

  constructor(private readonly options: WorldOptions) {
    this.prng = createPrng(options.seed);
    this.registry = new SubjectRegistry(this.prng.fork("registry"));
    for (const [k, fn] of Object.entries(options.generators ?? {})) {
      this.customKeyGenerators.set(k.toLowerCase(), fn);
    }
  }

  // -------------------------------------------------------------------------
  // withSubject / withSchema / withGenerators
  // -------------------------------------------------------------------------

  withSubject(subjectType: AnySubjectType): this {
    this.subjectTypes.set(subjectType.name, subjectType);
    return this;
  }

  withSchema<TSchema extends ZodTypeAny, TSubjectType extends AnySubjectType>(
    schema: TSchema,
    subjectType: TSubjectType,
    matchers?: Matchers<TSchema, SubjectData<TSubjectType>>,
  ): this;
  withSchema<TSchema extends ZodTypeAny>(
    schema: TSchema,
    subjectTypes: string | string[],
    matchers?: Matchers<TSchema, unknown>,
  ): this;
  withSchema(
    schema: ZodTypeAny,
    subjectTypes: AnySubjectType | string | string[],
    matchers?: Record<string, unknown>,
  ): this {
    let types: string[];
    if (typeof subjectTypes === "string") {
      types = [subjectTypes];
    } else if (Array.isArray(subjectTypes)) {
      types = subjectTypes as string[];
    } else {
      types = [(subjectTypes as AnySubjectType).name];
    }
    this.schemaRegs.push({
      schema,
      subjectTypes: types,
      matchers: (matchers ?? {}) as Record<string, MatcherFn<unknown, unknown>>,
    });
    return this;
  }

  withGenerators(map: Record<string, KeyGenerator>): this {
    for (const [k, fn] of Object.entries(map)) {
      this.customKeyGenerators.set(k.toLowerCase(), fn);
    }
    return this;
  }

  withKeyMap<T extends ZodTypeAny>(schema: T, map: SchemaKeyMap<T>): this {
    const existing = this.schemaKeyMaps.get(schema) ?? {};
    this.schemaKeyMaps.set(schema, {
      ...existing,
      ...(map as Record<string, (ctx: GeneratorContext) => unknown>),
    });
    return this;
  }

  // -------------------------------------------------------------------------
  // subject()
  // -------------------------------------------------------------------------

  subjects(type?: string): AnySubjectInstance[] {
    if (type === undefined) return [...this.allInstances];
    return this.allInstances.filter((s) => s._type === type);
  }

  populate(subjectType: AnySubjectType | string, count: number): this {
    const name = typeof subjectType === "string" ? subjectType : subjectType.name;
    for (let i = 0; i < count; i++) {
      this.subject(name);
    }
    return this;
  }

  subject(typeName: string): AnySubjectInstance {
    if (!this.subjectTypes.has(typeName)) {
      throw new Error(`Subject type '${typeName}' is not registered. Call .withSubject() first.`);
    }
    return this.createSubjectInstance(typeName);
  }

  // -------------------------------------------------------------------------
  // generate()
  // -------------------------------------------------------------------------

  generate<TSchema extends ZodTypeAny>(
    schema: TSchema,
    options?: GenerateOptions<input<TSchema>>,
  ): input<TSchema> {
    const d = getZodDef(schema);
    if (d.type === "array") {
      return this.generateArray(
        d.element!,
        schema,
        options as GenerateOptions<unknown[]> | undefined,
      ) as input<TSchema>;
    }
    return this.generateSingleItem(
      schema,
      options as GenerateOptions<unknown> | undefined,
    ) as input<TSchema>;
  }

  // -------------------------------------------------------------------------
  // Private: subject creation
  // -------------------------------------------------------------------------

  private createSubjectInstance(typeName: string): AnySubjectInstance {
    const subjectType = this.subjectTypes.get(typeName)!;
    const counter = (this.subjectCounters.get(typeName) ?? 0) + 1;
    this.subjectCounters.set(typeName, counter);

    const _id = `${typeName}#${counter}`;
    // Per-subject PRNG — stable regardless of call order on the world
    const subjectPrng = createPrng(fieldSeed(this.options.seed, _id, ""));

    const rawData: Record<string, unknown> = {};
    const instance: AnySubjectInstance = {
      _type: typeName,
      _id,
      data: rawData as SubjectData<AnySubjectType>,
      _relations: {},
    };
    this.allInstances.push(instance);

    const ctx: GeneratorContext = {
      prng: subjectPrng,
      subject: instance,
      registry: this.registry,
      fieldPath: "",
      optionalProbability: 0, // subject data always fully populated
      related: <T>(relName: string) => this.resolveRelation<T>(instance, relName),
      relatedTo: <T>(targetType: string, relName: string) =>
        this.resolveReverseRelation<T>(instance, targetType, relName),
    };

    // Apply key-based generators for subject fields so semantic field names
    // (firstName, lastName, email, etc.) produce meaningful values.
    const subjectShape = getZodDef(subjectType.schema).shape!;
    for (const [key, fieldSchema] of Object.entries(subjectShape)) {
      const fieldCtx: GeneratorContext = {
        ...ctx,
        prng: ctx.prng.fork(key),
        fieldPath: key,
      };
      const customGen = this.customKeyGenerators.get(key.toLowerCase());
      if (customGen !== undefined) {
        rawData[key] = customGen(fieldSchema, fieldCtx);
      } else {
        const subjectKeyMapFn = subjectType.keyMap?.[key];
        if (subjectKeyMapFn !== undefined) {
          rawData[key] = subjectKeyMapFn(fieldCtx.prng);
        } else {
          const keyResult = generateFromKey(key, fieldSchema, fieldCtx);
          rawData[key] =
            keyResult !== undefined ? keyResult : generateFromSchema(fieldSchema, fieldCtx);
        }
      }
    }
    // Pass 2: derived fields — overwrite base values using sibling field data.
    // World-level custom generators take priority and are not overridden.
    for (const [key, fn] of Object.entries(subjectType.derive ?? {})) {
      if (!this.customKeyGenerators.has(key.toLowerCase())) {
        const deriveCtx: GeneratorContext = {
          ...ctx,
          prng: ctx.prng.fork(`derive-${key}`),
        };
        rawData[key] = fn(rawData, deriveCtx);
      }
    }

    this.registry.store(typeName, instance.data); // store raw subject data, not the wrapper
    return instance;
  }

  // -------------------------------------------------------------------------
  // Private: query helpers
  // -------------------------------------------------------------------------

  private resolveRelation<T>(instance: AnySubjectInstance, relName: string): T {
    if (relName in instance._relations) {
      const cached = instance._relations[relName];
      if (cached === null) return undefined as unknown as T;
      if (Array.isArray(cached)) return cached.map((c) => c.data) as unknown as T;
      return (cached as AnySubjectInstance).data as unknown as T;
    }

    const subjectType = this.subjectTypes.get(instance._type)!;
    const relDef = subjectType.relations?.[relName];
    if (!relDef) {
      throw new Error(`Relation '${relName}' is not defined on subject type '${instance._type}'.`);
    }

    const relPrng = this.prng.fork(`rel-${instance._id}-${relName}`);
    const targetType = relDef.type;

    let existing = this.getInstancesOfType(targetType);
    let count = 0;
    switch (relDef.cardinality) {
      case "1":
        count = 1;
        break;
      case "0..1":
        count = relPrng.random() < 0.5 ? 1 : 0;
        break;
      case "0..n":
        count = relPrng.int(0, 3);
        break;
      case "1..n":
        count = relPrng.int(1, 3);
        break;
    }

    const selected: AnySubjectInstance[] = [];
    for (let i = 0; i < count; i++) {
      if (existing.length === 0) {
        this.createSubjectInstance(targetType);
        existing = this.getInstancesOfType(targetType);
      }
      selected.push(existing[relPrng.int(0, existing.length - 1)]!);
    }

    if (relDef.cardinality === "1" || relDef.cardinality === "0..1") {
      const result = selected[0] ?? null;
      instance._relations[relName] = result as any;
      return (result ? result.data : undefined) as unknown as T;
    } else {
      instance._relations[relName] = selected;
      return selected.map((s) => s.data) as unknown as T;
    }
  }

  private resolveReverseRelation<T>(
    instance: AnySubjectInstance,
    targetType: string,
    relName: string,
  ): T[] {
    const targets = this.getInstancesOfType(targetType);
    const results: AnySubjectInstance[] = [];

    for (const target of targets) {
      this.resolveRelation(target, relName); // Force resolve

      const related = target._relations[relName];
      if (Array.isArray(related)) {
        if (related.includes(instance)) results.push(target);
      } else if (related === instance) {
        results.push(target);
      }
    }

    return results.map((r) => r.data) as unknown as T[];
  }

  private getInstancesOfType(typeName: string): AnySubjectInstance[] {
    return this.allInstances.filter((s) => s._type === typeName);
  }

  private findRegsForSchema(schema: ZodTypeAny): SchemaReg[] {
    return this.schemaRegs.filter((r) => r.schema === schema);
  }

  private getTopologicallySortedTypes(): string[] {
    const visited = new Set<string>();
    const temp = new Set<string>();
    const order: string[] = [];

    const visit = (typeName: string) => {
      if (temp.has(typeName))
        throw new Error(`Circular dependency detected involving '${typeName}'`);
      if (visited.has(typeName)) return;

      temp.add(typeName);
      const subjectType = this.subjectTypes.get(typeName);
      if (subjectType?.relations) {
        for (const rel of Object.values(subjectType.relations)) {
          if (this.subjectTypes.has(rel.type)) {
            visit(rel.type);
          }
        }
      }
      temp.delete(typeName);
      visited.add(typeName);
      order.push(typeName);
    };

    for (const typeName of this.subjectTypes.keys()) {
      visit(typeName);
    }
    return order;
  }

  /**
   * Ensure every registered subject type has at least one instance.
   * Called before any subject-based generation so that matchers that call
   * `ctx.registry.pick(otherType)` always find data.
   */
  private ensureAllTypesHaveSubjects(): void {
    const order = this.getTopologicallySortedTypes();
    for (const typeName of order) {
      if (this.getInstancesOfType(typeName).length === 0) {
        this.createSubjectInstance(typeName);
      }
    }
  }

  /**
   * Build an ordered list of (instance, reg) pairs for all existing subjects
   * of the types referenced by `regs`.  Order: by registration order, then by
   * subject creation order within each type.
   */
  private buildPairs(regs: SchemaReg[]): SubjectRegPair[] {
    const pairs: SubjectRegPair[] = [];
    for (const reg of regs) {
      for (const typeName of reg.subjectTypes) {
        for (const instance of this.getInstancesOfType(typeName)) {
          pairs.push({ instance, reg });
        }
      }
    }
    return pairs;
  }

  /**
   * Flat list of subject type names in registration order (for cycling when
   * we need to create more subjects to satisfy a minimum array length).
   */
  private regTypeCycle(regs: SchemaReg[]): string[] {
    return regs.flatMap((r) => r.subjectTypes);
  }

  // -------------------------------------------------------------------------
  // Private: item generation
  // -------------------------------------------------------------------------

  private generateItemForSubject(
    schema: ZodTypeAny,
    instance: AnySubjectInstance,
    reg: SchemaReg,
    options?: GenerateOptions<unknown>,
  ): unknown {
    // Stable PRNG per subject — independent of which other subjects exist
    const itemPrng = this.prng.fork(instance._id);

    const subjectArg = {
      ...instance.data,
      _type: instance._type,
      _id: instance._id,
    } as SubjectMatcherArg<unknown>;

    const ctx: GeneratorContext = {
      prng: itemPrng,
      subject: instance,
      registry: this.registry,
      fieldPath: "",
      optionalProbability: this.options.optionalProbability ?? 0.2,
      related: <T>(relName: string) => this.resolveRelation<T>(instance, relName),
      relatedTo: <T>(targetType: string, relName: string) =>
        this.resolveReverseRelation<T>(instance, targetType, relName),
    };

    const result = this.generateObjectFields(schema, subjectArg, reg.matchers, ctx);

    let merged: unknown = result;
    if (options?.overrides) {
      merged = deepMerge(result, options.overrides);
    }
    if (options?.transform) {
      merged = options.transform(merged);
    }
    return merged;
  }

  /**
   * Generate all fields of an object schema, applying matchers first, then
   * falling back to key-based → schema-based for unmatched fields.
   */
  private generateObjectFields(
    schema: ZodTypeAny,
    subjectArg: SubjectMatcherArg<unknown>,
    matchers: Record<string, MatcherFn<unknown, unknown>>,
    ctx: GeneratorContext,
  ): Record<string, unknown> {
    const d = getZodDef(schema);

    // Non-object schema (shouldn't happen for registered schemas, but handle anyway)
    if (d.type !== "object") {
      return generateFromSchema(schema, ctx) as Record<string, unknown>;
    }

    const shape = d.shape!;
    const result: Record<string, unknown> = {};

    for (const [key, fieldSchema] of Object.entries(shape)) {
      const matcher = matchers[key];
      const fieldCtx: GeneratorContext = {
        ...ctx,
        prng: ctx.prng.fork(key),
        fieldPath: ctx.fieldPath ? `${ctx.fieldPath}.${key}` : key,
      };

      if (matcher) {
        result[key] = matcher(subjectArg, fieldCtx);
        continue;
      }

      // Unwrap optional/nullable so key-based generators see the inner schema,
      // and handle the absent-value probability here rather than deep inside
      // generateFromSchema where the field key is no longer available.
      const fd = getZodDef(fieldSchema);
      let innerSchema = fieldSchema;
      if (fd.type === "optional") {
        if (fieldCtx.prng.random() < (ctx.optionalProbability ?? 0.2)) {
          result[key] = undefined;
          continue;
        }
        innerSchema = fd.innerType ?? fieldSchema;
      } else if (fd.type === "nullable") {
        if (fieldCtx.prng.random() < (ctx.optionalProbability ?? 0.2)) {
          result[key] = null;
          continue;
        }
        innerSchema = fd.innerType ?? fieldSchema;
      }

      const keyMapFn = this.schemaKeyMaps.get(schema)?.[key];
      if (keyMapFn !== undefined) {
        result[key] = keyMapFn(fieldCtx);
        continue;
      }

      const customGen = this.customKeyGenerators.get(key.toLowerCase());
      if (customGen !== undefined) {
        result[key] = customGen(innerSchema, fieldCtx);
      } else {
        const keyResult = generateFromKey(key, innerSchema, fieldCtx);
        result[key] =
          keyResult !== undefined ? keyResult : generateFromSchema(innerSchema, fieldCtx);
      }
    }

    return result;
  }

  // -------------------------------------------------------------------------
  // Private: array generation
  // -------------------------------------------------------------------------

  private generateArray(
    innerSchema: ZodTypeAny,
    arraySchema: ZodTypeAny,
    options?: GenerateOptions<unknown[]>,
  ): unknown[] {
    const regs = this.findRegsForSchema(innerSchema);

    this.generationCounter++;
    const genPrng = this.prng.fork(`gen-${this.generationCounter}`);

    const [defMin, defMax] = this.options.defaultArrayLength ?? [1, 5];

    // -----------------------------------------------------------------------
    // Ad-hoc: no registrations — pure schema-based generation
    // -----------------------------------------------------------------------
    if (regs.length === 0) {
      let N = defMin;
      let max = defMax;
      for (const c of getCheckDefs(arraySchema)) {
        if (c.check === "length_equals") {
          N = c.length!;
          max = N;
          break;
        }
        if (c.check === "min_length" && c.minimum !== undefined) N = Math.max(N, c.minimum);
        if (c.check === "max_length" && c.maximum !== undefined) max = Math.min(max, c.maximum);
      }
      N = genPrng.int(Math.min(N, max), Math.max(N, max));
      return Array.from({ length: N }, (_, i) =>
        generateFromSchema(innerSchema, {
          prng: genPrng.fork(`[${i}]`),
          subject: undefined,
          registry: this.registry,
          fieldPath: `[${i}]`,
          optionalProbability: this.options.optionalProbability ?? 0.2,
          related: () => {
            throw new Error("Cannot call related() on ad-hoc generation. No active subject.");
          },
          relatedTo: () => {
            throw new Error("Cannot call relatedTo() on ad-hoc generation.");
          },
        }),
      );
    }

    // -----------------------------------------------------------------------
    // Registered schema: one item per subject
    // -----------------------------------------------------------------------

    // Ensure all registered types have at least one subject so that matchers
    // calling ctx.registry.pick(otherType) always find data.
    this.ensureAllTypesHaveSubjects();

    // Collect existing (instance, reg) pairs for this schema's subject types
    let pairs = this.buildPairs(regs);
    const existingCount = pairs.length;

    // Determine the minimum number of items required by the array constraints
    const minRequired = resolveMinRequired(arraySchema, defMin);
    const target = Math.max(existingCount, minRequired);

    // Create more subjects if needed, cycling through the registered types
    const typeCycle = this.regTypeCycle(regs);
    while (pairs.length < target) {
      const nextType = typeCycle[pairs.length % typeCycle.length]!;
      const newInstance = this.createSubjectInstance(nextType);
      const matchingReg = regs.find((r) => r.subjectTypes.includes(nextType))!;
      pairs.push({ instance: newInstance, reg: matchingReg });
    }

    // Generate one item per pair
    return pairs.map((pair) =>
      this.generateItemForSubject(
        innerSchema,
        pair.instance,
        pair.reg,
        options as GenerateOptions<unknown>,
      ),
    );
  }

  // -------------------------------------------------------------------------
  // Private: single-item generation
  // -------------------------------------------------------------------------

  private generateSingleItem(schema: ZodTypeAny, options?: GenerateOptions<unknown>): unknown {
    const regs = this.findRegsForSchema(schema);

    this.generationCounter++;

    // -----------------------------------------------------------------------
    // Ad-hoc: no registrations
    // -----------------------------------------------------------------------
    if (regs.length === 0) {
      const ctx: GeneratorContext = {
        prng: this.prng.fork(`adhoc-${this.generationCounter}`),
        subject: undefined,
        registry: this.registry,
        fieldPath: "",
        optionalProbability: this.options.optionalProbability ?? 0.2,
        related: () => {
          throw new Error("Cannot call related() on ad-hoc generation. No active subject.");
        },
        relatedTo: () => {
          throw new Error("Cannot call relatedTo() on ad-hoc generation.");
        },
      };

      // If a keyMap is registered for this schema, route through
      // generateObjectFields so the keyMap (and key-based heuristics) fire.
      const keyMap = this.schemaKeyMaps.get(schema);
      let result: unknown;
      if (keyMap !== undefined && getZodDef(schema).type === "object") {
        result = this.generateObjectFields(
          schema,
          undefined as unknown as SubjectMatcherArg<unknown>,
          {},
          ctx,
        );
      } else {
        result = generateFromSchema(schema, ctx);
      }

      if (options?.overrides) result = deepMerge(result, options.overrides);
      if (options?.transform) result = options.transform(result as input<typeof schema>);
      return result;
    }

    // -----------------------------------------------------------------------
    // Registered schema: pick the next subject via cycling
    // -----------------------------------------------------------------------

    this.ensureAllTypesHaveSubjects();

    let pairs = this.buildPairs(regs);

    // If, somehow, no pairs exist yet (type registered but not in subjectTypes),
    // create one on the fly.
    if (pairs.length === 0) {
      const firstType = regs[0]!.subjectTypes[0]!;
      if (this.subjectTypes.has(firstType)) {
        const inst = this.createSubjectInstance(firstType);
        pairs = [{ instance: inst, reg: regs[0]! }];
      }
    }

    // Cycle through pairs deterministically
    const idx = (this.generationCounter - 1) % pairs.length;
    const pair = pairs[idx]!;

    return this.generateItemForSubject(schema, pair.instance, pair.reg, options);
  }
}

// ---------------------------------------------------------------------------
// Public factory
// ---------------------------------------------------------------------------

/**
 * Create a new world with the given options.
 *
 * Register subject types and app schemas declaratively before calling
 * `generate`.  All generation is lazy and deterministic.
 *
 * @example
 * ```ts
 * const world = createWorld({ seed: 42 })
 *   .withSubject(PersonSubject)
 *   .withSchema(PersonApiSchema, 'person', {
 *     email: (s) => `${s.firstName[0]}.${s.lastName}@example.nl`.toLowerCase(),
 *   })
 * ```
 */
export function createWorld(options: WorldOptions): World {
  return new WorldImpl(options);
}
