/**
 * GENERATED by `pnpm build-samples` (site/scripts/build-samples.ts) — DO NOT EDIT.
 * Every type-link emitted across the docs samples (B126-R3). The dangling-link guard
 * (site/scripts/api-link-guard.ts) validates each `anchor` against the /docs/api anchor
 * set, so a twoslash-emitted dead type-link fails the build (B126-R6). Plain data (D13).
 */

export interface SampleLink {
  readonly text: string;
  readonly anchor: string;
  readonly sample: string;
}

export const SAMPLE_LINKS: ReadonlyArray<SampleLink> = [
  {
    text: "generate",
    anchor: "generate",
    sample: "getting-started-lead",
  },
  {
    text: "generate",
    anchor: "generate",
    sample: "getting-started-lead",
  },
  {
    text: "createWorld",
    anchor: "createWorld",
    sample: "getting-started-seeded-world",
  },
  {
    text: "createWorld",
    anchor: "createWorld",
    sample: "getting-started-seeded-world",
  },
  {
    text: "createWorld",
    anchor: "createWorld",
    sample: "getting-started-matchers",
  },
  {
    text: "createWorld",
    anchor: "createWorld",
    sample: "getting-started-matchers",
  },
  {
    text: "createWorld",
    anchor: "createWorld",
    sample: "getting-started-relations",
  },
  {
    text: "createWorld",
    anchor: "createWorld",
    sample: "getting-started-relations",
  },
];
